name: LunaziaClassementF
author: Arad119
version: 1.1.1
main: fr.arad119.lunazia.MFactionRanking
depend: [Factions]

commands:
  classement:
    description: Afficher le classement des factions.
    permission: classement.classement